apiVersion: v1
kind: service
metadata:
   name: nginx
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-svc-ports
    protocal: Tcp
    port: 80
    targetport: 80